extends:
  - '@commitlint/config-conventional'

rules:
  # Ensure type is one of the allowed types
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert

  # Ensure subject is not empty
  subject-empty:
    - 2
    - never

  # Ensure type is not empty
  type-empty:
    - 2
    - never

  # Subject should not end with a period
  subject-full-stop:
    - 2
    - never
    - '.'

  # Subject should be in lowercase
  subject-case:
    - 2
    - always
    - lower-case
